## 1. Create a 3x3x3 array with random values

In [1]:
import random
import numpy as np 
x = np.random.random((3, 3, 3))
print(x)

[[[0.35902572 0.67285754 0.86580825]
  [0.25677327 0.72071557 0.15663955]
  [0.06723579 0.53973899 0.45411431]]

 [[0.77822003 0.04542921 0.35508457]
  [0.30746568 0.97215473 0.79820564]
  [0.75113144 0.03306361 0.44819352]]

 [[0.66250577 0.89462986 0.08636046]
  [0.12992742 0.54917605 0.88219957]
  [0.50399796 0.11819602 0.17566199]]]


## 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
import numpy as np
x = np.diag([1, 2, 3, 4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


## 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [17]:
import numpy as np
x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 4. Normalize a 5x5 random matrix

In [21]:
import numpy as np
x= np.random.random((5,5))
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("normalizing the inputs we get:\n",x)

normalizing the inputs we get:
 [[0.39709235 0.15452038 0.68340225 0.33522103 0.71098338]
 [0.33093732 0.91224884 0.         0.50515166 0.07302127]
 [0.01377573 1.         0.54485457 0.76000669 0.52429092]
 [0.91842165 0.22203175 0.98980909 0.15662275 0.04011844]
 [0.49850731 0.37122605 0.09471602 0.19845641 0.99012806]]


## 5.  How to find common values between two arrays?

In [28]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


## 6.How to get the dates of yesterday, today and tomorrow?

In [1]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


## 7. Consider two random array A and B, check if they are equal

In [3]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 1 1 1 1 1]
Second array:
[1 1 1 0 0 1]
Test above two arrays are equal or not!
False


## 8.Create random vector of size 10 and replace the maximum value by 0

In [1]:
import numpy as np
x = np.random.random(15)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.47912915 0.28187635 0.51226218 0.2704522  0.43674658 0.89859686
 0.48727488 0.08439599 0.83698396 0.85331161 0.01206397 0.47189865
 0.0593065  0.81518736 0.56704167]
Maximum value replaced by 0:
[0.47912915 0.28187635 0.51226218 0.2704522  0.43674658 0.
 0.48727488 0.08439599 0.83698396 0.85331161 0.01206397 0.47189865
 0.0593065  0.81518736 0.56704167]


## 9. How to print all the values of an array?

import numpy as np<br /> 
a = np.array([0, 1, 2, 3])<br /> 
a<br /> 
we print the all the values using the above code<br /> 


## 14.How to get the n largest values of an array

In [10]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


## 15.How to create a record array from a regular array?

In [15]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)


## 13.How to find the most frequent value in an array?

In [17]:
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[2 9 1 4 5 0 7 2 5 7 8 1 1 0 9 2 5 7 6 7 1 2 2 1 0 7 9 5 9 6 1 2 6 8 1 7 8
 6 1 0]
Most frequent value in the above array:
1


## 10.Subtract the mean of each row of a matrix

In [19]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.66940477 0.28114039 0.01589291 0.47021098 0.8639263  0.16334421
  0.52660536 0.91673528 0.06088606 0.79167471]
 [0.48138755 0.0273591  0.96108143 0.06881227 0.002352   0.67809925
  0.30137686 0.58997496 0.25084535 0.12329442]
 [0.2827649  0.65742575 0.66021511 0.42367622 0.49670578 0.41639412
  0.26921302 0.76929804 0.18338611 0.54381989]
 [0.13515508 0.12609284 0.09670665 0.42778202 0.84853529 0.57326513
  0.06397254 0.95125621 0.60880821 0.9893506 ]
 [0.72281955 0.34130712 0.2251514  0.14021078 0.24939042 0.26680594
  0.63504807 0.70038846 0.03116614 0.40694477]]

Subtract the mean of each row of the said matrix:

[[ 0.19342267 -0.19484171 -0.46008918 -0.00577111  0.3879442  -0.31263789
   0.05062326  0.44075318 -0.41509604  0.31569261]
 [ 0.13292923 -0.32109922  0.61262311 -0.27964604 -0.34610632  0.32964093
  -0.04708146  0.24151664 -0.09761297 -0.2251639 ]
 [-0.187525    0.18713586  0.18992521 -0.04661367  0.02641589 -0.05389577
  -0.20107687  0.29900815 -0.2

## 12.How to get the diagonal of a dot product?

In [6]:
import numpy as np
x = np.diag([1, 2, 3, 4])
print(x)
k= np.diagonal(x)
l= np.diagonal(x)
np.dot(k,l)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


30

## 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?¶

In [7]:
import numpy as np
x = np.ones((3,3))
x = np.zeros((5,5),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]
